# Generated by Django 2.0.8 on 2020-05-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squarelet_auth_organizations', '0006_auto_20200527_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
