# Generated by Django 3.2.9 on 2023-06-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarelet_auth_organizations', '0007_delete_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='resources',
            field=models.JSONField(default=dict),
        ),
    ]
